In [1]:
# load libraries
import numpy as np
import pandas as pd

import sklearn
from sklearn.neighbors import NearestNeighbors

In [2]:
# load batting data
batting = pd.read_csv('mlb2014-batting.csv')
batting.columns = ['playerID', 'nameFirst', 'nameLast', 
                   'bats', 'throws', 'age', 'year', 
                   'stints', 'teamID', 'lg', 'G', 'tap', 
                   'AB', 'R', 'H', 'db', 'tr', 'HR', 
                   'RBI', 'SB', 'CS', 'BB', 'SO', 'IBB', 
                   'hbp', 'SH', 'SF', 'GIDP', 'avg', 'obp', 
                   'slg', 'woba', 'PRO', 'GURU', 'ROTO', 
                   'pos1', 'g1', 'pos2', 'g2', 'pos3', 
                   'g3', 'pos4', 'g4', 'pos5', 'g5', 
                   'baseball_prospectus_id', 'mlbam_id', 
                   'n2013']
print(batting.head())

    playerID  nameFirst nameLast bats throws   age  year  stints teamID  lg  \
0  abreubo01      Bobby    Abreu    L      R  40.0  2014       1    NYN  NL   
1  abreujo02       Jose    Abreu    R      R  27.0  2014       1    CHA  AL   
2  abreuto01       Tony    Abreu    B      R  29.0  2014       1    SFN  NL   
3  ackledu01     Dustin   Ackley    L      L  26.0  2014       1    SEA  AL   
4  adamecr01  Cristhian   Adames    S      R  22.0  2014       1    COL  NL   

   ...     g2  pos3  g3  pos4  g4  pos5  g5  baseball_prospectus_id  mlbam_id  \
0  ...    NaN   NaN NaN   NaN NaN   NaN NaN          ABREU19740311A  110029.0   
1  ...    NaN   NaN NaN   NaN NaN   NaN NaN          ABREU20140129A  547989.0   
2  ...    1.0   NaN NaN   NaN NaN   NaN NaN          ABREU19841113A  473234.0   
3  ...    NaN   NaN NaN   NaN NaN   NaN NaN         ACKLEY19880226A  554429.0   
4  ...    2.0   NaN NaN   NaN NaN   NaN NaN         ADAMES19910726A  542436.0   

   n2013  
0    NaN  
1    NaN  
2  53

In [3]:
# these are the hitting stats you want
#   [AB, AVG, HR]
t = [400, 300, 25]
print(t)

# matrix of values for those features
#X = batting.ix[:,(13, 25, 18)].values
X = batting.ix[:,[13, 25, 18]].values
print(X[0:5])

[400, 300, 25]
[[ 12   0  14]
 [ 80   0 107]
 [  0   0   0]
 [ 64   3  65]
 [  1   0   0]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


In [4]:
# find the nearest neighbors for the whole set
print('Neighbors')
nbrs = NearestNeighbors(n_neighbors=5).fit(X)
distances, indices = nbrs.kneighbors([t])

# get just the indices of the nearest neighbors
print(indices)

Neighbors
[[162 487 597 440  93]]


In [5]:
# see what the recommendations are
print("Recommendations")
for i in indices:
    print(batting.iloc[i])

Recommendations
      playerID nameFirst   nameLast bats throws   age  year  stints teamID  \
162  doziebr01     Brian     Dozier    R      R  27.0  2014       1    MIN   
487  rendoan01   Anthony     Rendon    R      R  24.0  2014       1    WAS   
597  troutmi01      Mike      Trout    R      R  22.0  2014       1    LAA   
440  pencehu01    Hunter      Pence    R      R  31.0  2014       1    SFN   
93   carpema01      Matt  Carpenter    L      L  28.0  2014       1    STL   

     lg   ...      g2  pos3  g3  pos4  g4  pos5  g5  baseball_prospectus_id  \
162  AL   ...     NaN   NaN NaN   NaN NaN   NaN NaN         DOZIER19870515A   
487  NL   ...    28.0   NaN NaN   NaN NaN   NaN NaN         RENDON19900606A   
597  AL   ...     NaN   NaN NaN   NaN NaN   NaN NaN          TROUT19910807A   
440  NL   ...     NaN   NaN NaN   NaN NaN   NaN NaN          PENCE19830413A   
93   NL   ...     2.0   NaN NaN   NaN NaN   NaN NaN      CARPENTER19851126A   

     mlbam_id   n2013  
162  572821.0   