In [1]:
# load libraries
import numpy as np
import pandas as pd

import sklearn
from sklearn.neighbors import NearestNeighbors

In [3]:
# load batting data
pitching = pd.read_csv('mlb2014-pitching.csv')
pitching.columns = ['playerID', 'nameFirst', 'nameLast', 'throws', 'age', 'year', 'stints', 'teamID', 'LG', 'POS1', 
                   'W', 'L', 'CG', 'Sh', 'GP', 'GS', 'SV', 'GF', 'IPOuts', 'IP', 'ERA', 'HA', 'ER', 'HRA', 'BBA', 
                   'SOA', 'IBBA', 'WP', 'HPBA', 'BK', 'BFP', 'RA', 'CMD', 'DOM', 'CTL', 'HR9', 'babip', 'WHIP', 
                   'WRIP', 'HRBIB', 'RAVG', 'FIP', 'DERA', 'babipera', 'STUFF', 'GURU', 'ROTO', 
                    'baseball_prospectus_id', 'mlbam_id', 'n2013'
]
print(pitching.head())

    playerID nameFirst nameLast throws  age  year  stints teamID  LG POS1  \
0   abadfe01  Fernando     Abad      L   29  2014       1    OAK  AL   LP   
1  aceveal01   Alfredo   Aceves      R   32  2014       1    NYA  AL   BP   
2  achteaj01      A.J.   Achter      R   26  2014       1    MIN  AL   BP   
3  adamsau01    Austin    Adams      R   28  2014       1    CLE  AL   AP   
4  adamsmi03      Mike    Adams      R   36  2014       1    PHI  NL   BP   

    ...      RAVG     FIP  DERA  babipera  STUFF   GURU      ROTO  \
0   ...     1.73    3.32   3.19     3.61      86  268.0   $14.01    
1   ...     6.52    6.36   5.89     5.37       9    3.0    $1.34    
2   ...     5.73    5.47   5.30     5.71       0   16.0    $1.17    
3   ...     9.00    4.34   4.24     7.87       9    1.0     $-      
4   ...     3.86    2.93   2.83     5.62     154   67.0    $3.96    

   baseball_prospectus_id  mlbam_id   n2013  
0           ABAD19851217A    472551   769.0  
1         ACEVES19821208A    4

In [14]:
# these are the hitting stats you want
#   [W, L, ERA]
t = [12, 6, 300]

# matrix of values for those features
#X = pitching.ix[:,(11, 12, 21)].values
X = pitching.iloc[:,[11, 12, 21]].values
print(X[0:5])

[[ 4  0 34]
 [ 2  0 23]
 [ 0  0 14]
 [ 0  0  9]
 [ 1  0 16]]


In [8]:
# find the nearest neighbors for the whole set
print('Neighbors')
nbrs = NearestNeighbors(n_neighbors=10).fit(X)
distances, indices = nbrs.kneighbors([t])

# get just the indices of the nearest neighbors
print(indices)

Neighbors
[[500  76 578 643 184 405 299 130 351 256]]


In [10]:
# see what the recommendations are
print("Recommendations")
for i in indices:
    print(pitching.iloc[i])

Recommendations
      playerID nameFirst   nameLast throws  age  year  stints teamID  LG POS1  \
500  priceda01     David      Price      L   29  2014       2    DET  AL   SP   
76   buehrma01      Mark    Buehrle      L   36  2014       1    TOR  AL   SP   
578  shielja02     James    Shields      R   33  2014       1    KCA  AL   SP   
643  verlaju01    Justin  Verlander      R   32  2014       1    DET  AL   SP   
184  eovalna01    Nathan    Eovaldi      R   25  2014       1    MIA  NL   SP   
405  mccarbr01   Brandon   McCarthy      R   31  2014       2    NYA  AL   SP   
299  hugheph01    Philip     Hughes      R   29  2014       1    MIN  AL   SP   
130  colonba01   Bartolo      Colon      R   42  2014       1    NYN  NL   SP   
351  leakemi01      Mike      Leake      R   27  2014       1    CIN  NL   SP   
256  guthrje01    Jeremy    Guthrie      R   36  2014       1    KCA  AL   SP   

      ...      RAVG     FIP  DERA  babipera  STUFF   GURU      ROTO  \
500   ...     3.62   